/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SevenSegController */

#ifndef _Included_SevenSegController
#define _Included_SevenSegController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SevenSegController
 * Method:    init7Seg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SevenSegController_init7Seg
  (JNIEnv *, jobject);

/*
 * Class:     SevenSegController
 * Method:    show
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SevenSegController_show
  (JNIEnv *, jobject, jint);

/*
 * Class:     SevenSegController
 * Method:    showWithDp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SevenSegController_showWithDp
  (JNIEnv *, jobject, jint);

/*
 * Class:     SevenSegController
 * Method:    init7Seg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SevenSegController_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
