/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../74HC595/74HC595.h"
#include "../../../74HC595/7seg/7seg.h"
/* Header for class SevenSegController */
hc595_handle_t handle;
/*
 * Class:     SevenSegController
 * Method:    init7Seg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SevenSegController_init7Seg
  (JNIEnv * ptr_jni, jobject obj_java){
      Drv7SegInit(&handle);
  }

/*
 * Class:     SevenSegController
 * Method:    show
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SevenSegController_show
  (JNIEnv * ptr_jni, jobject obj_java, jint digit){
      Drv7SegDisp(&handle, digit);
  }

/*
 * Class:     SevenSegController
 * Method:    showWithDp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SevenSegController_showWithDp
  (JNIEnv * ptr_jni, jobject obj_java, jint digit){
      Drv7SegDispWithDp(&handle,digit);
  }

/*
 * Class:     SevenSegController
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SevenSegController_clear
  (JNIEnv * ptr_jni, jobject obj_java){
      Drv7SegClear(&handle);
  }
