/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <wiringPi.h>

/* Header for class LedController */


/*
 * Class:     LedController
 * Method:    setHigh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LedController_setHigh
  (JNIEnv * ptr_jni, jobject obj_java, jint addr){
      digitalWrite(addr,HIGH);
  }

/*
 * Class:     LedController
 * Method:    setLow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LedController_setLow
  (JNIEnv * ptr_jni, jobject obj_java, jint addr){
      digitalWrite(addr,LOW);
  }

/*
 * Class:     LedController
 * Method:    cfgOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LedController_cfgOutput
  (JNIEnv * ptr_jni, jobject obj_java, jint addr){
    //Init wirePi
    wiringPiSetup();
    pinMode(addr, OUTPUT);
  }

