/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LedController */

#ifndef _Included_LedController
#define _Included_LedController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LedController
 * Method:    setHigh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LedController_setHigh
  (JNIEnv *, jobject, jint);

/*
 * Class:     LedController
 * Method:    setLow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LedController_setLow
  (JNIEnv *, jobject, jint);

/*
 * Class:     LedController
 * Method:    cfgOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LedController_cfgOutput
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
